apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: exam-tomasrojka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: nathansegers/big_data_and_ai-24_may_api:versie1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: exam-tomasrojka
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
